<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>JohnDavisDotDev.IL.Templates</PackageId>
    <PackageVersion>1.0.6</PackageVersion>
    <Title>John Davis .NET IL Templates</Title>
    <Authors>John Davis</Authors>
    <Description>Templates for .NET Intermediate Language (IL) projects.</Description>
    <PackageTags>IL, .NET, Templates</PackageTags>
    <PackageProjectUrl>https://github.com/johndavisdotdev/ILTemplates</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <!-- Keep package type as 'Template' to show the package as a template package on nuget.org and make your template available in dotnet new search.-->
    <PackageType>Template</PackageType>
    <TargetFramework>net10.0</TargetFramework>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup>
    <LocalizeTemplates>false</LocalizeTemplates>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.TemplateEngine.Tasks" Version="*" PrivateAssets="all" IsImplicitlyDefined="true"/>
  </ItemGroup>

  <ItemGroup>
    <Content Include="content\**\*" Exclude="content\**\bin\**;content\**\obj\**" />
    <Compile Remove="**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <Target Name="CreateManifestResourceNames" />

</Project>
